//! Autogenerated weights for pallet_token_non_fungible
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-07-29, STEPS: `50`, REPEAT: 200, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/web3games-node
// benchmark
// pallet
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_token_non_fungible
// --extrinsic
// *
// --steps
// 50
// --repeat
// 200
// --template
// ./.maintain/w3g-weight-template.hbs
// --output
// ./pallets/token-non-fungible/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_token_non_fungible.
pub trait WeightInfo {
    fn create_token() -> Weight;
    fn mint() -> Weight;
    fn burn() -> Weight;
    fn approve() -> Weight;
    fn set_approve_for_all() -> Weight;
    fn transfer_from() -> Weight;
}

/// Weights for pallet_token_non_fungible using the Web3Games node and recommended hardware.
pub struct W3GWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for W3GWeight<T> {
    // Storage: TokenNonFungible Tokens (r:1 w:1)
    // Storage: System Account (r:1 w:1)
    fn create_token() -> Weight {
        (32_289_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    // Storage: TokenNonFungible Tokens (r:1 w:0)
    // Storage: TokenNonFungible Owners (r:1 w:1)
    // Storage: TokenNonFungible Balances (r:1 w:1)
    // Storage: TokenNonFungible TotalSupply (r:1 w:1)
    // Storage: TokenNonFungible AllTokensIndex (r:0 w:1)
    // Storage: TokenNonFungible OwnedTokens (r:0 w:1)
    // Storage: TokenNonFungible AllTokens (r:0 w:1)
    // Storage: TokenNonFungible OwnedTokensIndex (r:0 w:1)
    fn mint() -> Weight {
        (42_819_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(7 as Weight))
    }
    // Storage: TokenNonFungible Owners (r:1 w:1)
    // Storage: TokenNonFungible Balances (r:1 w:1)
    // Storage: TokenNonFungible TotalSupply (r:1 w:1)
    // Storage: TokenNonFungible AllTokensIndex (r:1 w:1)
    // Storage: TokenNonFungible AllTokens (r:1 w:1)
    // Storage: TokenNonFungible OwnedTokensIndex (r:1 w:1)
    // Storage: TokenNonFungible TokenApprovals (r:0 w:1)
    // Storage: TokenNonFungible OwnedTokens (r:0 w:1)
    fn burn() -> Weight {
        (59_728_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(6 as Weight))
            .saturating_add(T::DbWeight::get().writes(8 as Weight))
    }
    // Storage: TokenNonFungible Owners (r:1 w:0)
    // Storage: TokenNonFungible TokenApprovals (r:0 w:1)
    fn approve() -> Weight {
        (20_149_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
    // Storage: TokenNonFungible OperatorApprovals (r:0 w:1)
    fn set_approve_for_all() -> Weight {
        (15_971_000 as Weight)
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
    // Storage: TokenNonFungible Owners (r:1 w:1)
    // Storage: TokenNonFungible Balances (r:2 w:2)
    // Storage: TokenNonFungible OwnedTokensIndex (r:1 w:1)
    // Storage: TokenNonFungible TokenApprovals (r:0 w:1)
    // Storage: TokenNonFungible OwnedTokens (r:0 w:2)
    fn transfer_from() -> Weight {
        (55_443_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(7 as Weight))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn create_token() -> Weight {
        (32_289_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
    }
    fn mint() -> Weight {
        (42_819_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(7 as Weight))
    }
    fn burn() -> Weight {
        (59_728_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(6 as Weight))
            .saturating_add(RocksDbWeight::get().writes(8 as Weight))
    }
    fn approve() -> Weight {
        (20_149_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(1 as Weight))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
    }
    fn set_approve_for_all() -> Weight {
        (15_971_000 as Weight)
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
    }
    fn transfer_from() -> Weight {
        (55_443_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(7 as Weight))
    }
}
