//! Autogenerated weights for pallet_token_fungible
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-07-29, STEPS: `50`, REPEAT: 200, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/web3games-node
// benchmark
// pallet
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_token_fungible
// --extrinsic
// *
// --steps
// 50
// --repeat
// 200
// --template
// ./.maintain/w3g-weight-template.hbs
// --output
// ./pallets/token-fungible/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_token_fungible.
pub trait WeightInfo {
    fn create_token() -> Weight;
    fn mint() -> Weight;
    fn approve() -> Weight;
    fn burn() -> Weight;
    fn transfer() -> Weight;
    fn transfer_from() -> Weight;
}

/// Weights for pallet_token_fungible using the Web3Games node and recommended hardware.
pub struct W3GWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for W3GWeight<T> {
    // Storage: TokenFungible Tokens (r:1 w:1)
    // Storage: System Account (r:1 w:1)
    fn create_token() -> Weight {
        (32_369_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    // Storage: TokenFungible Tokens (r:1 w:1)
    // Storage: TokenFungible Balances (r:1 w:1)
    fn mint() -> Weight {
        (25_268_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    // Storage: TokenFungible Balances (r:1 w:0)
    // Storage: TokenFungible Allowances (r:1 w:1)
    fn approve() -> Weight {
        (21_810_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
    }
    // Storage: TokenFungible Tokens (r:1 w:1)
    // Storage: TokenFungible Balances (r:1 w:1)
    fn burn() -> Weight {
        (22_864_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    // Storage: TokenFungible Balances (r:2 w:2)
    fn transfer() -> Weight {
        (24_899_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(2 as Weight))
    }
    // Storage: TokenFungible Allowances (r:1 w:1)
    // Storage: TokenFungible Balances (r:2 w:2)
    fn transfer_from() -> Weight {
        (30_457_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(3 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn create_token() -> Weight {
        (32_369_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
    }
    fn mint() -> Weight {
        (25_268_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
    }
    fn approve() -> Weight {
        (21_810_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
    }
    fn burn() -> Weight {
        (22_864_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
    }
    fn transfer() -> Weight {
        (24_899_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(2 as Weight))
    }
    fn transfer_from() -> Weight {
        (30_457_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(3 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
    }
}
